### ISSUE TITLE
Add website to description

### ISSUE THREAD

**Issue by logsol** [antoineschmitt/dywapitchtrack#2]
Hey, why don't you add the description about the project from your website to the description of this repository or paste it to the README? It was quite helpful for me to get some contextual information. 

http://schmittmachine.com/dywapitchtrack/

I am pasting it here for future reference:

> Pitch tracking C library
> 
> open source (MIT licence)
> 
> The dywapitchtrack library computes the pitch of an audio stream in real time. The pitch is the main frequency of the waveform (the ‘note’ being played or sung). It is expressed as a float in Hz.
> 
> Unlike the human ear, pitch detection is difficult to achieve for computers. Many algorithms have been designed and experimented, but there is no ‘best’ algorithm. They all depend on the context and the tradeoffs acceptable in terms of speed and latency. The context includes the quality and ‘cleanness’ of the audio : obviously polyphonic sounds (multiple instruments playing different notes at the same time) are extremely difficult to track, percussive or noisy audio has no pitch, most real-life audio have some noisy moments, some instruments have a lot of harmonics, etc…
> 
> The dywapitchtrack is based on a custom-tailored algorithm which is of very high quality: both very accurate (precision < 0.05 semitones), very low latency (< 23 ms) and very low error rate. It has been thoroughly tested on human voice.
> 
> It can best be described as a dynamic wavelet algorithm (dywa):
> 
> The heart of the algorithm is a very powerful wavelet algorithm, described in a paper by Eric Larson and Ross Maddox : “[Real-Time Time-Domain Pitch Tracking Using Wavelets](http://courses.physics.illinois.edu/phys406/NSF_REU_Reports/2005_reu/Real-Time_Time-Domain_Pitch_Tracking_Using_Wavelets.pdf)” of UIUC Physics.
> 
> This central algorithm has been improved by adding dynamic tracking, to reduce the common problems of frequency-halving and voiced/unvoiced errors. This dynamic tracking explains the need for a tracking structure (dywapitchtracker). The dynamic tracking assumes that the main function dywapitch_computepitch is called repeatedly, as it follows the pitch over time and makes assumptions about human voice capabilities and reallife conditions (as documented inside the code).
> 
> Note : The algorithm currently assumes a 44100Hz audio sampling rate. If you use a different samplerate, you can just multiply the resulting pitch by the ratio between your samplerate and 44100.
> 
> See the dywapitchtrack.h file for the library API documentation.
> 
> History :
> This algorithm has been designed during a mission for a customer. As I had kept the author’s rights on the source code, I eventually decided to make this code public and open source, because it is of really high quality. This algorithm has been extensively tested, especially it has been included in an Adobe Director Xtra (plugin), [asPitchDetect Xtra](http://schmittmachine.com/aspitchdetect-xtra/), that has been distributed widely for a few years.
> 
> I hope that it can be used with pleasure and efficiency in your project.
> 
> Thank you
> Antoine Schmitt April 2010

**Comment by antoineschmitt** [comment]
Done ! Thanks for the idea..
